### ISSUE TITLE
@CascadeSensitive  标注string  integer等类型，会导致数据变成空。

### ISSUE THREAD

**Issue by 9997766** [allurx/desensitization#35]
@CascadeSensitive  标注string  integer等类型，会导致数据变成空。

**Comment by allurx** [comment]
@9997766`@CascadeSensitive`这个注解会去创建一个与目标对象class相同的对象，会依次查找无参构造器、自己注册的`InstanceCreator`，如果都没有的话就会通过java提供的`Unsafe`这个类来创建对象，最终导致你提到的`String`，`Integer`为空，实际上这个注解的应用场景应该是放在自己编写的类上面，然后这个类的某些field上有一些敏感注解，最终进行级联脱敏。你可以参考工程中的测试用例，里面有各个敏感注解详细的用法。
