### ISSUE TITLE
PhoneNumberDesensitizer对长度不足3的字符串脱敏抛出异常

### ISSUE THREAD

**Issue by ghost** [allurx/desensitization#38]
String phone = "a";
String phone2 = Sensitive.desensitize(phone, new TypeToken<@PhoneNumberSensitive String>() {});
System.out.println(phone2);

会抛出异常：
Exception in thread "main" java.lang.IllegalArgumentException: startOffset: 3, endOffset: 4, target: a

分析：
AbstractCharSequenceDesensitizer.desensitize 对于startOffset >= str.length()的都会抛出错误

建议：
增强脱敏注解的鲁棒性，例如如下场景，从数据库中读出大量的电话号码，可能某些脏数据，电话号码长度为“”， 电话长度不足，此时脱敏不应该抛出异常，而是另外方式，例如：全部替换为占位符，或不处理。

**Comment by allurx** [comment]
我写这个库的时候考虑过输入数据是否合法的问题，最终还是决定每个内置的[Desensitizer](https://github.com/Allurx/desensitization/tree/master/src/main/java/red/zyc/desensitization/desensitizer)不做任何数据异常的判断，因为一个数据是不是合法在不同的业务场景可能有不同的判断，而这个库只做数据本身的脱敏处理，过滤异常数据应该放到上游去做。假设现在我有一个包含异常数据的`List`，我只想对其中正常的数据进行脱敏，有以下三种解决方案：
```java
// 原始数据
List<String> list = Stream.of("", null, "123", "12345678900").collect(Collectors.toList());
```
1. 在上游过滤原始数据然后脱敏过滤后的数据（个人认为这应该是最合理的解决方案）
```java
List<String> filtered = list.stream().filter(s -> s != null && !s.isBlank() && s.length() == 11).collect(Collectors.toList());

List<String> r1 = Sensitive.desensitize(filtered, new TypeToken<List<@PhoneNumberSensitive String>>() {
});
```
2. 定义过滤Condition并使用内置的Desensitizer脱敏
```java
class MyCondition implements Condition<String> {

      @Override
      public boolean required(String target) {
          return target != null && !target.isBlank() && target.length() == 11;
      }
 }

List<String> r2 = Sensitive.desensitize(list, new TypeToken<List<@PhoneNumberSensitive(condition = MyCondition.class) String>>() {
});
```
3.替换内置的Desensitizer，自己实现脱敏逻辑
```java
class MyDesensitizer extends PhoneNumberDesensitizer {

    @Override
    public String desensitize(String target, PhoneNumberSensitive annotation) {
        return target != null && !target.isBlank() && target.length() == 11 ?
                super.desensitize(target, annotation) : target;
    }
}

List<String> r3 = Sensitive.desensitize(list, new TypeToken<List<@PhoneNumberSensitive(desensitizer = MyDesensitizer.class) String>>() {
});
```
希望可以帮助到你:smiley:

**Comment by ghost** [comment]
感谢
